### ISSUE TITLE
graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Driky** [OscarYuen/go-graphql-starter#12]
Hi,

I just got that error while trying the step described on the readme (using an auth token). I'm really new to the go world so I probably have done some thing stupid but just in case here is the error and the query and auth parameters that created it.

### query
```
{
  users{
    totalCount
  }
}
```

### user
`email: "test@tester.com", password: "test"`

token used 
`'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkX2F0IjoiMjAxOC0wNC0zMFQxMzo1MToyOS45NzczOTlaIiwiZXhwIjo4OTgzOTU4OTk2LCJpZCI6IlltSnFiR1k0T1RWcWJXOXdabXQyWW1WbWREQT0iLCJpc3MiOiJnby1ncmFwaHFsLXN0YXJ0ZXIifQ.bTE8-DnSYA1BRMgc1QdtyJilxZpQDbfbSqPwxVVTQMo',`

### error
```
2018/04/30 14:08:36 graphql: panic occurred: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
github.com/graph-gophers/graphql-go/log.(*DefaultLogger).LogPanic(0xc26c78, 0x9aa2c0, 0xc4200abb00, 0x8b6180, 0xbf7e40)
        /home/newtrax/workspace/experiments/go/src/github.com/graph-gophers/graphql-go/log/log.go:21 +0x77
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2.1(0xc4200c4180, 0x9aa2c0, 0xc4200abb00, 0xc420066ef8, 0xc42000c220)
        /home/newtrax/workspace/experiments/go/src/github.com/graph-gophers/graphql-go/internal/exec/exec.go:161 +0x87
panic(0x8b6180, 0xbf7e40)
        /usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
github.com/OscarYuen/go-graphql-starter/resolver.(*Resolver).Users(0xc26c78, 0x9aa2c0, 0xc4200abb90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/newtrax/workspace/experiments/go/src/github.com/OscarYuen/go-graphql-starter/resolver/user_query.go:36 +0xff
reflect.Value.call(0x8c31c0, 0xc26c78, 0xa13, 0x9412cc, 0x4, 0xc4200abc20, 0x2, 0x2, 0x3, 0xc4200abc20, ...)
        /usr/lib/go-1.10/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x8c31c0, 0xc26c78, 0xa13, 0xc4200abc20, 0x2, 0x2, 0xa13, 0x2, 0xc420093200)
        /usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection.func2(0xc4200c4180, 0x9aa2c0, 0xc4200abb00, 0xc42000c220, 0xc420036a00, 0xc420066f40, 0x9aa2c0, 0xc4200abb90, 0x0)
        /home/newtrax/workspace/experiments/go/src/github.com/graph-gophers/graphql-go/internal/exec/exec.go:183 +0x372
github.com/graph-gophers/graphql-go/internal/exec.execFieldSelection(0x9aa2c0, 0xc4200abb00, 0xc4200c4180, 0xc420036a00, 0xc42000c220, 0x1)
        /home/newtrax/workspace/experiments/go/src/github.com/graph-gophers/graphql-go/internal/exec/exec.go:193 +0x1aa
github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections.func1(0xc4200bca90, 0xc4200c4180, 0x9aa2c0, 0xc4200abb00, 0x0, 0xc420036a00)
        /home/newtrax/workspace/experiments/go/src/github.com/graph-gophers/graphql-go/internal/exec/exec.go:74 +0x16c
created by github.com/graph-gophers/graphql-go/internal/exec.(*Request).execSelections
        /home/newtrax/workspace/experiments/go/src/github.com/graph-gophers/graphql-go/internal/exec/exec.go:70 +0x476
```

**Comment by OscarYuen** [comment]
Thanks for reporting error.
I found there is an error in encoding the cursor for user connections. 
I have fixed It and should be okay now.
